services:
  api:
    container_name: tech-challenge-8soat
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0'"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}
