apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: thiagopelizoni/fastfood-api:latest
        command: ["/bin/bash", "-c", "bundle exec ruby lib/db_setup.rb && bin/rails server"]
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: RAILS_ENV
        - name: RAILS_MAX_THREADS
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: RAILS_MAX_THREADS
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_PORT