apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: init-db
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_DB
        command: ['sh', '-c', 'until pg_isready -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB; do echo waiting for database; sleep 2; done;']
      containers:
      - name: api-container
        image: api:latest
        command: ["/bin/bash", "-c", "/usr/bin/entrypoint.sh"]
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: RAILS_ENV
        - name: RAILS_MAX_THREADS
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: RAILS_MAX_THREADS
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: fastfood-api-secrets
              key: POSTGRES_PORT
        volumeMounts:
        - name: api-volume
          mountPath: /api
      volumes:
      - name: api-volume
        persistentVolumeClaim:
          claimName: api-pvc
---
