apiVersion: v1
kind: Secret
metadata:
  name: fastfood-api-secrets
type: Opaque
data:
  RAILS_ENV: ZGV2ZWxvcG1lbnQ=
  RAILS_MAX_THREADS: MTY=
  RAILS_PORT: MzAwMA==
  POSTGRES_USER: YXBp
  POSTGRES_PASSWORD: ZlhURlFFUnpKVWVkNkg=
  POSTGRES_DB: YXBp
  POSTGRES_HOST: ZGI=
  POSTGRES_PORT: NTQzMg==
