default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>